CREATE TABLE Users (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL
);

CREATE TABLE Documents (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  is_public BOOLEAN DEFAULT False,
  html_content JSON DEFAULT {},
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(3) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
)

CREATE TABLE Comments (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  content VARCHAR()
  index VARCHAR()
  FOREIGN KEY (user_id) REFERENCES Users(id) on DELETE CASCADE,
  FOREIGN KEY (doc_id) REFERENCES Documents(id) on DELETE CASCADE,
)

