topcv:
  "url": https://www.topcv.vn/tim-viec-lam-{job}?sba={page}
  "find_jobs_tag": "div"
  "find_jobs_class": "job-item-search-result"
  "title_tag": "h3"
  "title_class": "title"
  "company_tag": "a"
  "company_class": "company"
  "location_tag": "label"
  "location_class": "address"
  "salary_tag": "label"
  "salary_class": "title-salary"
  "req_tag": "div"
  "req_class": "job-detail__information-detail--content"
  "req_split": "Yêu cầu ứng viên"

linkedin:
  "url": https://www.linkedin.com/jobs/search/?geoId=104195383&keywords={job}&origin=JOBS_HOME_KEYWORD_HISTORY&refresh=true&start={range}
  "find_jobs_tag": "div"
  "find_jobs_class": "base-card relative w-full hover:no-underline focus:no-underline base-card--link base-search-card base-search-card--link job-search-card"
  "title_tag": "a"
  "title_class": "base-card__full-link absolute top-0 right-0 bottom-0 left-0 p-0 z-[2]"
  "company_tag": "h4"
  "company_class": "base-search-card__subtitle"
  "location_tag": "span"
  "location_class": "job-search-card__location"
  "salary_tag": "div"
  "salary_class": "salary"
  "req_tag": "div"
  "req_class": "show-more-less-html__markup show-more-less-html__markup--clamp-after-5 relative overflow-hidden"
  "req_split": "Requirements"

